# ref. https://github.com/yutakatay/dotfiles/blob/master/.github/workflows/test.yml
name: CI

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: apt-get update && apt-get install -y git sudo
      - name: Install dotfiles
        run: .bin/dotsinstaller.sh install --no-gui
      - uses: actions/checkout@v1
      - name: vint
        uses: reviewdog/action-vint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.

  centos:
    runs-on: ubuntu-latest
    container: centos:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: yum install -y git sudo
      - name: Install dotfiles
        run: .bin/dotsinstaller.sh install --no-gui

  fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: dnf clean all && dnf install -y git sudo
      - name: Install dotfiles
        run: .bin/dotsinstaller.sh install --no-gui

  alpine:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: apk add git sudo bash
      - name: Install dotfiles
        run: .bin/dotsinstaller.sh install --no-gui

  arch:
    runs-on: ubuntu-latest
    container: archlinux/base:latest
    steps:
      - uses: actions/checkout@v1
      - name: Update packages
        run: pacman -Syu --noconfirm
      - name: Install required packages
        run: pacman -S --noconfirm git sudo
      - name: Install dotfiles
        run: .bin/dotsinstaller.sh install
      - name: Add user
        run: useradd builduser -m
      - name: Add sudoer
        run: echo 'builduser ALL=(ALL) ALL' >> /etc/sudoers
      - name: Change password
        run: passwd -d builduser
      - name: Install arch software
        run: sudo -u builduser bash -c '.bin/arch-extra-setup.sh'
      - name: Install vim plugins
        run: vim +PlugInstall +qall
      - name: Install neovim plugins
        run: nvim +PlugInstall +qall

  lint:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v1
      - name: Update packages
        run: apt-get update
      - name: Install packages for install repository
        run: apt-get install -y git sudo software-properties-common python-pip
      - name: Install required repository
        run: apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe"
      - name: Install required packages
        run: apt-get update; apt-get install -y shellcheck
      - name: Install vint
        run: pip install -q vim-vint
      - name: Execute vint
        run: test $(vint  ~/.vimrc ~/.vim/rc/* ~/.vim/rc/myplugins/* | grep -v "keyconfig.vim" | grep -v "scriptencoding" | grep -v ".*\.nvim.*E492.*" | tee -a /dev/stderr | wc -l)  -le 1
      - name: Execute shellcheck
        run: test $(shellcheck  -f gcc ~/.zshrc ~/.zsh/rc/* | grep -v "SC1036\|SC1056\|SC1070\|SC1072\|SC1073\|SC1083\|SC2034\|SC2139\|SC2148\|SC1090\|SC1117\|SC2206\|SC1009\|SC2016\|SC2046\|SC2154" | tee -a /dev/stderr | wc -l) -le 1